name: condorsmotors
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  dio: ^5.4.1 # Cliente HTTP moderno y potente
  http_parser: ^4.0.2
  mobile_scanner: ^6.0.7
  shared_preferences: ^2.5.2
  logging: ^1.3.0
  google_fonts: ^6.2.1 # Usamos Source Sans 3 como fuente principal
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.19.0
  msix: ^3.16.8
  dart_code_metrics: ^4.19.2
  win_toast: ^0.3.0 # Notificaciones nativas en Windows 10/11
  provider: ^6.1.4
  fl_chart: ^0.66.2
  url_launcher: ^6.3.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Configuración de íconos en la raíz, no dentro de flutter:
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/condor-motors-logo.webp"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/condor-motors-logo.webp"
  remove_alpha_ios: false
  windows:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"
  web:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"

# Configuración para el instalador MSIX de Windows
msix_config:
  display_name: Condor Motors
  publisher_display_name: Condor Motors
  identity_name: com.condorsmotors.condorsmotors
  msix_version: 1.0.0.0
  logo_path: assets/images/condor-motors-logo.webp
  capabilities: internetClient
  toast_activator:
    clsid: "936C39FC-6BBC-4A57-B8F8-7C627E401B2F"
    arguments: "-ToastActivated"
    display_name: "Condor Motors Proformas"

# COMENTARIOS PARA CREAR INSTALADOR MSIX:
# 1. Asegúrate de tener instalado el SDK de Windows 10
# 2. Para crear el instalador MSIX, ejecuta este comando en la terminal:
#    flutter pub run msix:create
# 3. Si quieres personalizar la creación, puedes usar parámetros adicionales:
#    flutter pub run msix:create --store (para Microsoft Store)
#    flutter pub run msix:create --install (para crear e instalar directamente)
#    flutter pub run msix:create --build-windows (para construir y luego crear el MSIX)
# 4. El instalador MSIX se generará en la carpeta /build/windows/runner/Release
# 5. Recuerda que para que funcionen las notificaciones toast en Windows,
#    necesitas usar el instalador MSIX (no funciona ejecutando en modo debug)

# COMENTARIOS PARA CREAR APK (ANDROID):
# 1. Para crear un APK de depuración (debug):
#    flutter build apk --debug
#    El APK se generará en build/app/outputs/flutter-apk/app-debug.apk
#
# 2. Para crear un APK de producción (release):
#    flutter build apk --release
#    El APK se generará en build/app/outputs/flutter-apk/app-release.apk
#
# 3. Para crear un APK optimizado por arquitectura (más pequeño):
#    flutter build apk --split-per-abi --release
#    Esto generará APKs separados para cada arquitectura (arm64-v8a, armeabi-v7a, x86_64)
#
# 4. Para instalar directamente en un dispositivo conectado:
#    flutter install
#
# 5. Para generar un bundle para Google Play Store:
#    flutter build appbundle
#    El bundle se generará en build/app/outputs/bundle/release/app-release.aab

flutter:
  uses-material-design: true

  assets:
    - assets/images/condor-motors-logo.webp
    - assets/fonts/source_sans_3/
    # ... otros assets ...

  fonts:
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/source_sans_3/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_3/SourceSans3-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/source_sans_3/SourceSans3-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_3/SourceSans3-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/source_sans_3/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/source_sans_3/SourceSans3-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/source_sans_3/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_3/SourceSans3-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/source_sans_3/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_3/SourceSans3-SemiBoldItalic.ttf
          weight: 600
          style: italic
